id: P009633
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2232
  title: འབྲུག་པའི་ཆོས་མཛོད་ཆེན་པོ་བསམ་འཕེལ་ནོར་བུའི་བང་མཛོད།
  author: ''
  volumes:
    dfbd7e178cf947dfaa3418b7a6d68280:
      image_group_id: I3CN2235
      title: ''
      volume_number: 1
      total_pages: 624
    29bd7ace5d0149f19f86b5564702250a:
      image_group_id: I3CN2236
      title: ''
      volume_number: 2
      total_pages: 626
    3ad0b5bd4d294f09bdf929e083b4e73f:
      image_group_id: I3CN2237
      title: ''
      volume_number: 3
      total_pages: 649
    cc1defdc0fff49b7b22002ece1b064f7:
      image_group_id: I3CN2238
      title: ''
      volume_number: 4
      total_pages: 843
    86228e19f169435c8f92daa64c384eeb:
      image_group_id: I3CN2239
      title: ''
      volume_number: 5
      total_pages: 681
    97c94b26d7bf46a5964979620ae25ed8:
      image_group_id: I3CN2240
      title: ''
      volume_number: 6
      total_pages: 584
    d3b6551ac86b4af5b3e9e409b6c93774:
      image_group_id: I3CN2241
      title: ''
      volume_number: 7
      total_pages: 726
    da1b883d1e464ee38d79f5ccc18a5a26:
      image_group_id: I3CN2242
      title: ''
      volume_number: 8
      total_pages: 664
    f17df27a0cff48ef9f16db5eb2d390ca:
      image_group_id: I3CN2243
      title: ''
      volume_number: 9
      total_pages: 674
    51f98246224743c29e2044ffeca7cf3a:
      image_group_id: I3CN2244
      title: ''
      volume_number: 10
      total_pages: 648
    fc41c1a06c4c45e3919a2760d428c86b:
      image_group_id: I3CN2245
      title: ''
      volume_number: 11
      total_pages: 606
    51ca8f67ae2248389555d87bc84eeb14:
      image_group_id: I3CN2246
      title: ''
      volume_number: 12
      total_pages: 600
    4e9784da959646b88d2d4029bdd1a1a1:
      image_group_id: I3CN2247
      title: ''
      volume_number: 13
      total_pages: 630
    15b7bbb6337048e79d758624f1538c07:
      image_group_id: I3CN2248
      title: ''
      volume_number: 14
      total_pages: 602
    b3806e60dfb2410e8e828a8cc1101941:
      image_group_id: I3CN2249
      title: ''
      volume_number: 15
      total_pages: 604
    acf002ab5d294c73a10395391680e1a9:
      image_group_id: I3CN2250
      title: ''
      volume_number: 16
      total_pages: 670
    07f00c1e4c854dd8bec08b457d182f53:
      image_group_id: I3CN2251
      title: ''
      volume_number: 17
      total_pages: 604
    29f5731f5cb64f3f8889f3497ba373fa:
      image_group_id: I3CN2252
      title: ''
      volume_number: 18
      total_pages: 603
    b1fdc889f9304c50bb2032d365c55fa6:
      image_group_id: I3CN2253
      title: ''
      volume_number: 19
      total_pages: 608
    15c0a3439d184fae956b440a2a5bdcc2:
      image_group_id: I3CN2254
      title: ''
      volume_number: 20
      total_pages: 584
    6b3b29af8c554fc294d0d18a1eef63f3:
      image_group_id: I3CN2255
      title: ''
      volume_number: 21
      total_pages: 576
    dcaf43aefd1743a7827b6d91a4d9b327:
      image_group_id: I3CN2256
      title: ''
      volume_number: 22
      total_pages: 546
    9e230ee23cb747fbbb3f0a584bdd902f:
      image_group_id: I3CN2257
      title: ''
      volume_number: 23
      total_pages: 646
    6bc0ed444ee44308b52b51cf79f43772:
      image_group_id: I3CN2258
      title: ''
      volume_number: 24
      total_pages: 638
    144206921389457286726eeb075dd909:
      image_group_id: I3CN2259
      title: ''
      volume_number: 25
      total_pages: 596
    8afb1f72e6bd48e899053728510ed153:
      image_group_id: I3CN2260
      title: ''
      volume_number: 26
      total_pages: 545
    c31abfc42247406db712f41a1a4c1dec:
      image_group_id: I3CN2261
      title: ''
      volume_number: 27
      total_pages: 613
    25763959cdb140ad9972f5735e5af3d8:
      image_group_id: I3CN2262
      title: ''
      volume_number: 28
      total_pages: 543
    023ca2eb764140709775be6f687626a1:
      image_group_id: I3CN2263
      title: ''
      volume_number: 29
      total_pages: 512
    70ec4daf5b95484d874e46411cf3f4f0:
      image_group_id: I3CN2264
      title: ''
      volume_number: 30
      total_pages: 616
    0bfbd8f83ee648579f91c3b24992e8a3:
      image_group_id: I3CN2265
      title: ''
      volume_number: 31
      total_pages: 570
    834325e50eff4db6b22606fd9423e4d1:
      image_group_id: I3CN2266
      title: ''
      volume_number: 32
      total_pages: 568
    ac99a54e29754dc4aa38333017af7d15:
      image_group_id: I3CN2267
      title: ''
      volume_number: 33
      total_pages: 644
    7a9295ce59894102bc49173496acf6d6:
      image_group_id: I3CN2268
      title: ''
      volume_number: 34
      total_pages: 730
    02b11ebdcdd549da9e96bb12a10779d5:
      image_group_id: I3CN2269
      title: ''
      volume_number: 35
      total_pages: 660
    9c9b05a53fd34e5396e99b97a470addd:
      image_group_id: I3CN2270
      title: ''
      volume_number: 36
      total_pages: 594
    cf9c126ffb1848cda6d855141d72461e:
      image_group_id: I3CN2271
      title: ''
      volume_number: 37
      total_pages: 656
    7e31c026e8a845249a4abfe3bdbf5047:
      image_group_id: I3CN2272
      title: ''
      volume_number: 38
      total_pages: 586
    ba2e60eef0464b92b9d5e83dde14b12f:
      image_group_id: I3CN2273
      title: ''
      volume_number: 39
      total_pages: 592
    2dd65966f66d4fe4b678d4e9cbd4271b:
      image_group_id: I3CN2274
      title: ''
      volume_number: 40
      total_pages: 570
    c8a587497e154b1f96941430eec561c7:
      image_group_id: I3CN2275
      title: ''
      volume_number: 41
      total_pages: 582
    b4ad82a930cc4157ade981288064069d:
      image_group_id: I3CN2276
      title: ''
      volume_number: 42
      total_pages: 484
    b62286dabaff47fb82f97f4d6a07e3c2:
      image_group_id: I3CN2277
      title: ''
      volume_number: 43
      total_pages: 454
    0e3e2231f1ba40c39be8335147fec499:
      image_group_id: I3CN2278
      title: ''
      volume_number: 44
      total_pages: 790
    e4fe75cf6bb44aec83132b5fa268de7e:
      image_group_id: I3CN2279
      title: ''
      volume_number: 45
      total_pages: 592
    f342298018bf4bbd80906173e5723d63:
      image_group_id: I3CN2280
      title: ''
      volume_number: 46
      total_pages: 582
    6eb805e63775449aa8be0d36e3cfcacf:
      image_group_id: I3CN2281
      title: ''
      volume_number: 47
      total_pages: 550
    3676830310a84dc5b4990ddbee0c0843:
      image_group_id: I3CN2282
      title: ''
      volume_number: 48
      total_pages: 494
    05f3b1c215774d48a4e3acb44829f671:
      image_group_id: I3CN2283
      title: ''
      volume_number: 49
      total_pages: 814
    0f4f366438174808bc0b3da2894ddc0e:
      image_group_id: I3CN2284
      title: ''
      volume_number: 50
      total_pages: 510
    9ba685c5fa874297a4a8919af16997da:
      image_group_id: I3CN2285
      title: ''
      volume_number: 51
      total_pages: 526
    a0384f30f5b54c479a888b4c9790a4ca:
      image_group_id: I3CN2286
      title: ''
      volume_number: 52
      total_pages: 636
    85677730619542118ded2f909b0a7410:
      image_group_id: I3CN2287
      title: ''
      volume_number: 53
      total_pages: 602
    201e593b967b4659861f16a580f2cfca:
      image_group_id: I3CN2288
      title: ''
      volume_number: 54
      total_pages: 700
    f7798021d90f4585a999f25f5a70e9da:
      image_group_id: I3CN2289
      title: ''
      volume_number: 55
      total_pages: 620
    958aac31c2804848802ce5317d856668:
      image_group_id: I3CN2290
      title: ''
      volume_number: 56
      total_pages: 616
    00eb4c9f2b654bb0982aa1d1ccc9bb90:
      image_group_id: I3CN2291
      title: ''
      volume_number: 57
      total_pages: 682
    96f0434c17464a19bde2a17a6121b47b:
      image_group_id: I3CN2292
      title: ''
      volume_number: 58
      total_pages: 672
    d7fe6c9ec96b4e97a35ba4d63a23d380:
      image_group_id: I3CN2293
      title: ''
      volume_number: 59
      total_pages: 676
    c9ed921e1b554dcc9abc920d089df702:
      image_group_id: I3CN2294
      title: ''
      volume_number: 60
      total_pages: 620
    b8b2d41946604946a7128160904177f1:
      image_group_id: I3CN2295
      title: ''
      volume_number: 61
      total_pages: 932
    1e5c862098814e2fbf0616b710eea401:
      image_group_id: I3CN2296
      title: ''
      volume_number: 62
      total_pages: 872
    e4a78ead127b4f219c724c2bac891137:
      image_group_id: I3CN2297
      title: ''
      volume_number: 63
      total_pages: 494
    e048ade0348b4b9a9a5e52bd6c85ae26:
      image_group_id: I3CN2298
      title: ''
      volume_number: 64
      total_pages: 626
    ec4a0911976f417295e19f77c99d1525:
      image_group_id: I3CN2299
      title: ''
      volume_number: 65
      total_pages: 654
    e95be4889b164f0e801a758799867e5a:
      image_group_id: I3CN2300
      title: ''
      volume_number: 66
      total_pages: 624
    a8ac128d55e043c4b06715485f2557bd:
      image_group_id: I3CN2301
      title: ''
      volume_number: 67
      total_pages: 630
    3c0bcc09e37f4b2a84ab33af7045803e:
      image_group_id: I3CN2302
      title: ''
      volume_number: 68
      total_pages: 666
    ab88e44991c34604b8ad818e3e7e9312:
      image_group_id: I3CN2303
      title: ''
      volume_number: 69
      total_pages: 612
    ec9ffc2a01bc4e839b4173867b826555:
      image_group_id: I3CN2304
      title: ''
      volume_number: 70
      total_pages: 672
    ef6680909cb74dc8a4eabae98ad751c4:
      image_group_id: I3CN2305
      title: ''
      volume_number: 71
      total_pages: 606
    190f891b09ad4c2b8e224dafb70c7fb5:
      image_group_id: I3CN2306
      title: ''
      volume_number: 72
      total_pages: 512
    66ffcf014e1745f580a194fa047a03aa:
      image_group_id: I3CN2307
      title: ''
      volume_number: 73
      total_pages: 640
    bfcb441c04d7489d87ee4d95ae815d67:
      image_group_id: I3CN2308
      title: ''
      volume_number: 74
      total_pages: 632
    4fa1f69cb7b84aeeb613b0558adebf14:
      image_group_id: I3CN2309
      title: ''
      volume_number: 75
      total_pages: 604
    246b02c1e2134efa84709f84a898dc26:
      image_group_id: I3CN2310
      title: ''
      volume_number: 76
      total_pages: 428
    c49fc303eca44f5284d16e4f50950b20:
      image_group_id: I3CN2311
      title: ''
      volume_number: 77
      total_pages: 450
    50a8cec9efc245199c173de895e620b1:
      image_group_id: I3CN2312
      title: ''
      volume_number: 78
      total_pages: 570
    4e304b82495744dcbcbe5eacf2e21450:
      image_group_id: I3CN2313
      title: ''
      volume_number: 79
      total_pages: 636
    f7bf60728d56485694dc03dc4be327f3:
      image_group_id: I3CN2314
      title: ''
      volume_number: 80
      total_pages: 606
    4c2df0b52e0b4884a6fa51f4f8eca553:
      image_group_id: I3CN2315
      title: ''
      volume_number: 81
      total_pages: 586
    4d1c50bf94ce4c47a2dd003b762c158f:
      image_group_id: I3CN2316
      title: ''
      volume_number: 82
      total_pages: 664
    259309c97523464b83f3aa4aa8ce3646:
      image_group_id: I3CN2317
      title: ''
      volume_number: 83
      total_pages: 616
    806390d38c624a5fa0641a911f330209:
      image_group_id: I3CN2318
      title: ''
      volume_number: 84
      total_pages: 622
    60eb7d6c9db5436b891daffc468ba491:
      image_group_id: I3CN2319
      title: ''
      volume_number: 85
      total_pages: 600
    eca8708512784e39823f4189d5a35ec6:
      image_group_id: I3CN2320
      title: ''
      volume_number: 86
      total_pages: 644
    58f52aa4ff464606853d779339c63436:
      image_group_id: I3CN2321
      title: ''
      volume_number: 87
      total_pages: 646
    319669c9df2746dbaacdb35c2fec6f34:
      image_group_id: I3CN2322
      title: ''
      volume_number: 88
      total_pages: 553
    e7f160f654484f268c9257fe107f6ab1:
      image_group_id: I3CN2323
      title: ''
      volume_number: 89
      total_pages: 451
    5ffe586816204db2b3a2c23b764dac6a:
      image_group_id: I3CN2324
      title: ''
      volume_number: 90
      total_pages: 678
    a5c95d98a78a413c928faf196e8df7fc:
      image_group_id: I3CN2325
      title: ''
      volume_number: 91
      total_pages: 637
    075e305bdb60462b8aa57cfdcbf78310:
      image_group_id: I3CN2326
      title: ''
      volume_number: 92
      total_pages: 679
    5faed5220c6e493c9d58c44933522246:
      image_group_id: I3CN2327
      title: ''
      volume_number: 93
      total_pages: 658
    ad81c875d3c24ca9aa1e3114ad8a737e:
      image_group_id: I3CN2328
      title: ''
      volume_number: 94
      total_pages: 528
    59d151d9932d4111b2a004553be70084:
      image_group_id: I3CN2329
      title: ''
      volume_number: 95
      total_pages: 580
    6751dce57b104728997f30e217194875:
      image_group_id: I3CN2330
      title: ''
      volume_number: 96
      total_pages: 513
    e40132cf3a5c469ab4642eb3521c39f8:
      image_group_id: I3CN2331
      title: ''
      volume_number: 97
      total_pages: 434
    6696665d086f4f3ea133093471b7d3de:
      image_group_id: I3CN2332
      title: ''
      volume_number: 98
      total_pages: 493
    a44b731df0da404bada81cb9d467bb04:
      image_group_id: I3CN2333
      title: ''
      volume_number: 99
      total_pages: 777
    c0d84a6c992c400fb63248e0d5d5f000:
      image_group_id: I3CN2334
      title: ''
      volume_number: 100
      total_pages: 565
    d32f09726c164f04938c45df8a47e3b0:
      image_group_id: I3CN2335
      title: ''
      volume_number: 101
      total_pages: 1093
    d95b4a1241644e5e9957f7334dfa17e3:
      image_group_id: I3CN2336
      title: ''
      volume_number: 102
      total_pages: 560
    5fdb6e45d6b14447a6b08096d679950f:
      image_group_id: I3CN2337
      title: ''
      volume_number: 103
      total_pages: 620
    c8121aba62844703a32c2669e64593e8:
      image_group_id: I3CN2338
      title: ''
      volume_number: 104
      total_pages: 709
    99a795420a5e478685d8f1f739af3abe:
      image_group_id: I3CN2339
      title: ''
      volume_number: 105
      total_pages: 603
    a9b56d20926845eeafc4915ec49f58f1:
      image_group_id: I3CN2340
      title: ''
      volume_number: 106
      total_pages: 838
    991e967cff07414fb8a590fd88daca86:
      image_group_id: I3CN2341
      title: ''
      volume_number: 107
      total_pages: 660
    7df423f0f28b4451ab72ae0fff6d5e08:
      image_group_id: I3CN2342
      title: ''
      volume_number: 108
      total_pages: 556
    d34355fe4ecd4286846549acbf289ac7:
      image_group_id: I3CN2343
      title: ''
      volume_number: 109
      total_pages: 640
    bcc3818bf449463cb6ec3404e9540c19:
      image_group_id: I3CN2344
      title: ''
      volume_number: 110
      total_pages: 675
    b086e3ef378343658c694b04013a138c:
      image_group_id: I3CN2345
      title: ''
      volume_number: 111
      total_pages: 646
    de94e3f3ff394b9d83edcd42b1f2dcf4:
      image_group_id: I3CN2346
      title: ''
      volume_number: 112
      total_pages: 715
    918a693669b146e1b4c923a17c9ef6c2:
      image_group_id: I3CN2347
      title: ''
      volume_number: 113
      total_pages: 518
    f810ad7db16843d6b316b4a50bc0fbc7:
      image_group_id: I3CN2348
      title: ''
      volume_number: 114
      total_pages: 969
    843ebf97c6be476f8b1c803b1e4ac823:
      image_group_id: I3CN2349
      title: ''
      volume_number: 115
      total_pages: 391
    7a8136bae17347f3bdb489468d9dbf7e:
      image_group_id: I3CN2350
      title: ''
      volume_number: 116
      total_pages: 594
